# Workflow per costruire e pubblicare un sito Next.js su GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Eseguito ogni volta che fai un push sul branch `main`
  push:
    branches: ["main"]

  # Ti permette di eseguire questo workflow manualmente dalla tab Actions
  workflow_dispatch:

# Imposta i permessi per GITHUB_TOKEN per permettere il deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permetti un solo deploy concorrente, annullando quelli precedenti
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Lavoro di build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Lavoro di deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

